vlma-webapp/src/main/java/org/videolan/vlma/web/controller/server/ServerAdapterAddController.java
/*
 * Copyright (C) 2006-2008 the VideoLAN team
 *
 * This file is part of VLMa.
 *
 * VLMa is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * VLMa is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with VLMa. If not, see <http://www.gnu.org/licenses/>.
 *
 */

package org.videolan.vlma.web.controller.server;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.validation.BindException;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.SimpleFormController;
import org.videolan.vlma.Data;
import org.videolan.vlma.exception.AlreadyExistsException;
import org.videolan.vlma.model.Adapter;
import org.videolan.vlma.model.DVBSAdapter;
import org.videolan.vlma.model.Server;

public class ServerAdapterAddController extends SimpleFormController {

    private Data data;

    public void setData(Data data) {
        this.data = data;
    }

    @SuppressWarnings("unchecked")
    @Override
    public ModelAndView onSubmit(Object command) throws Exception {
        String adapterName = ((ServerAdapterAdd) command).getName();
        int serverId = ((ServerAdapterAdd) command).getServer();
        Server server = data.getServer(serverId);
        for (Adapter adapter : server.getAdapters()) {
            if (adapter.getName().equals(adapterName))
                throw new AlreadyExistsException("Server " + server.getName() + " already has an adapter whose name is " + adapterName);
        }
        String type = ((ServerAdapterAdd) command).getType();
        Class<Adapter> forName = (Class<Adapter>) Class.forName(type);
        Class<Adapter> clazz = forName;
        Adapter a = clazz.newInstance();
        a.setName(adapterName);
        a.setServer(server);
        server.addAdapter(a);
        if (a instanceof DVBSAdapter) {
            int satelliteId = ((ServerAdapterAdd) command).getSatellite();
            ((DVBSAdapter) a).setSatellite(data.getSatellite(satelliteId));
        }
        data.update(server);
        return new ModelAndView(getSuccessView(), "server", server.getId());
    }

    @Override
    protected Object formBackingObject(HttpServletRequest request)
            throws ServletException {
        ServerAdapterAdd serversAdapterAdd = new ServerAdapterAdd();
        serversAdapterAdd.setName("");
        serversAdapterAdd.setServer(Integer.parseInt(request
                .getParameter("server")));
        serversAdapterAdd.setType("DVB-T");
        serversAdapterAdd.setSatellite(null);
        return serversAdapterAdd;
    }

    @SuppressWarnings("unchecked")
    @Override
    protected ModelAndView showForm(HttpServletRequest arg0,
            HttpServletResponse arg1, BindException arg2, Map arg3)
            throws Exception {
        Server server = data.getServer(Integer.parseInt(arg0
                .getParameter("server")));
        Map<String, Object> m = new HashMap<String, Object>();
        m.put("server", server);
        m.put("satellites", data.getSatellites());
        return super.showForm(arg0, arg1, arg2, m);
    }

}

vlma-webapp/src/main/java/org/videolan/vlma/web/controller/server/ServerAdapterRemoveController.java
/*
 * Copyright (C) 2006-2008 the VideoLAN team
 *
 * This file is part of VLMa.
 *
 * VLMa is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * VLMa is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with VLMa. If not, see <http://www.gnu.org/licenses/>.
 *
 */

package org.videolan.vlma.web.controller.server;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.validation.BindException;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.SimpleFormController;
import org.videolan.vlma.Data;
import org.videolan.vlma.model.Adapter;
import org.videolan.vlma.model.Server;

public class ServerAdapterRemoveController extends SimpleFormController {

    private Data data;

    public void setData(Data data) {
        this.data = data;
    }

    @Override
    public ModelAndView onSubmit(Object command) throws Exception {
        int serverId = ((ServerAdapterAdd) command).getServer();
        String name = ((ServerAdapterAdd) command).getName();
        Server server = data.getServer(serverId);
        Iterator<Adapter> it = server.getAdapters().iterator();
        while (it.hasNext()) {
            Adapter a = it.next();
            if (a.getName().equals(name))
                it.remove();
        }
        data.update(server);
        return new ModelAndView(getSuccessView(), "server", server.getId());
    }

    @Override
    protected Object formBackingObject(HttpServletRequest request)
            throws ServletException {
        ServerAdapterAdd serversAdapterRemove = new ServerAdapterAdd();
        int server = Integer.parseInt(request.getParameter("server"));
        String name = request.getParameter("adapter");
        serversAdapterRemove.setServer(server);
        serversAdapterRemove.setName(name);
        return serversAdapterRemove;
    }

    @SuppressWarnings("unchecked")
    @Override
    protected ModelAndView showForm(HttpServletRequest arg0,
            HttpServletResponse arg1, BindException arg2, Map arg3)
            throws Exception {
        int serverId = Integer.parseInt(arg0.getParameter("server"));
        Server server = data.getServer(serverId);
        Adapter adapter = null;
        for (Adapter a : server.getAdapters()) {
            if (a.getName().equals(arg0.getParameter("adapter"))) {
                adapter = a;
            }
        }
        Map<String, Object> m = new HashMap<String, Object>();
        m.put("server", server);
        m.put("adapter", adapter);
        return super.showForm(arg0, arg1, arg2, m);
    }

}

vlma-webapp/src/main/java/org/videolan/vlma/web/controller/server/ServerAddController.java
/*
 * Copyright (C) 2006-2008 the VideoLAN team
 *
 * This file is part of VLMa.
 *
 * VLMa is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * VLMa is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with VLMa. If not, see <http://www.gnu.org/licenses/>.
 *
 */

package org.videolan.vlma.web.controller.server;

import java.net.UnknownHostException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.SimpleFormController;
import org.springframework.web.servlet.view.RedirectView;
import org.videolan.vlma.Data;
import org.videolan.vlma.model.Adapter;
import org.videolan.vlma.model.FilesAdapter;
import org.videolan.vlma.model.Server;
import org.videolan.vlma.model.StreamAdapter;

public class ServerAddController extends SimpleFormController {

    private Data data;

    public Data getData() {
        return data;
    }

    public void setData(Data data) {
        this.data = data;
    }

    @Override
    public ModelAndView onSubmit(Object command) throws Exception {
        String serverName = ((ServerAdd) command).getName();
        Server server = new Server();
        server.setName(serverName);
        server.setAddress(((ServerAdd) command).getAddress());
        Adapter filesAdapter = new FilesAdapter();
        filesAdapter.setName("files-adapter");
        filesAdapter.setServer(server);
        Adapter streamAdapter = new StreamAdapter();
        streamAdapter.setName("stream-adapter");
        streamAdapter.setServer(server);
        /* Add automatically the file-adapter and the stream-adapter
        when creating a new server. */
        server.addAdapter(filesAdapter);
        server.addAdapter(streamAdapter);
        data.add(server);
        return new ModelAndView(new RedirectView(getSuccessView()));
    }

    @Override
    protected Object formBackingObject(HttpServletRequest request)
            throws ServletException, UnknownHostException {
        ServerAdd serversAdd = new ServerAdd();
        serversAdd.setName("vls");
        serversAdd.setAddress("");
        return serversAdd;
    }

    @Override
    protected ModelAndView handleRequestInternal(HttpServletRequest arg0,
            HttpServletResponse arg1) throws Exception {
        return super.handleRequestInternal(arg0, arg1);
    }

}

vlma-webapp/src/main/java/org/videolan/vlma/web/controller/server/ServerListController.java
/*
 * Copyright (C) 2006-2008 the VideoLAN team
 *
 * This file is part of VLMa.
 *
 * VLMa is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * VLMa is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with VLMa. If not, see <http://www.gnu.org/licenses/>.
 *
 */

package org.videolan.vlma.web.controller.server;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;
import org.videolan.vlma.Data;

public class ServerListController implements Controller {

    public ModelAndView handleRequest(HttpServletRequest arg0,
            HttpServletResponse arg1) throws Exception {
        ModelAndView mav = new ModelAndView();
        mav.addObject("servers", data.getServers());
        mav.addObject("action", arg0.getParameter("action"));
        return mav;
    }

    private Data data;

    public Data getData() {
        return data;
    }

    public void setData(Data data) {
        this.data = data;
    }

}

vlma-webapp/src/main/java/org/videolan/vlma/web/controller/server/ServerMonitoringController.java
/*
 * Copyright (C) 2008 the VideoLAN team
 *
 * This file is part of VLMa.
 *
 * VLMa is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * VLMa is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with VLMa. If not, see <http://www.gnu.org/licenses/>.
 *
 */

package org.videolan.vlma.web.controller.server;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;
import org.videolan.vlma.Data;

public class ServerMonitoringController implements Controller {

    public ModelAndView handleRequest(HttpServletRequest arg0,
            HttpServletResponse arg1) throws Exception {
        ModelAndView mav = new ModelAndView();
        mav.addObject("servers", data.getServers());
        return mav;
    }

    private Data data;

    public Data getData() {
        return data;
    }

    public void setData(Data data) {
        this.data = data;
    }

}

vlma-webapp/src/main/java/org/videolan/vlma/web/controller/server/ServerViewController.java
/*
 * Copyright (C) 2006-2008 the VideoLAN team
 *
 * This file is part of VLMa.
 *
 * VLMa is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * VLMa is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with VLMa. If not, see <http://www.gnu.org/licenses/>.
 *
 */

package org.videolan.vlma.web.controller.server;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;
import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.mvc.Controller;
import org.videolan.vlma.Data;
import org.videolan.vlma.model.Server;

public class ServerViewController implements Controller {

    private static final Logger logger = Logger.getLogger(ServerViewController.class);

    public ModelAndView handleRequest(HttpServletRequest arg0,
            HttpServletResponse arg1) throws Exception {
        Server server = data.getServer(Integer.parseInt(arg0
                .getParameter("server")));
        ModelAndView mav = new ModelAndView();
        mav.addObject("server", server);
        try {
            String vlcVersion = data.getVlcVersion(server);
            mav.addObject("vlcVersion", vlcVersion);
        } catch(IOException e) {
            mav.addObject("vlcVersion", null);
            logger.error("Cannot retrieve VLC version", e);
        }
        try {
            List<String> logs = data.getVlcLogTail(server);
            mav.addObject("vlcLogs", logs);
        } catch(IOException e) {
            mav.addObject("vlcLogs", null);
            logger.error("Cannot retrieve VLC logs", e);
        }
        try {
            Long uptime = data.getVlcUptime(server);
            if(uptime != null)
                mav.addObject("vlcUptime", new TimeSpan(uptime));
            else
                mav.addObject("vlcUptime", null);
        } catch(IOException e) {
            mav.addObject("vlcUptime", null);
            logger.error("Cannot retrieve VLC uptime", e);
        }
        Boolean graphsEnabled = !"NONE".equals(data.getString("vlc.monitor.impl"));
        mav.addObject("graphsEnabled", graphsEnabled);
        return mav;
    }

    private Data data;

    public Data getData() {
        return data;
    }

    public void setData(Data data) {
        this.data = data;
    }

    public static class TimeSpan {

        private long millis;
        private static final String TIME_FORMAT = "HH:mm:ss";

        public TimeSpan(long millis) {
            this.millis = millis;
        }

        public long getDays() {
            return millis / (1000 * 60 * 60 * 24);
        }

        public String getHours() {
            long hoursMillis = millis % (1000 * 60 * 60 * 24);
            Date date = new Date(hoursMillis);
            // Don't store the dateformat in a static field because
            // DateFormat is not thread safe
            return new SimpleDateFormat(TIME_FORMAT).format(date);
        }
    }

}

vlma-webapp/src/main/webapp/WEB-INF/jsp/server/quicklinks.jsp
<%@ include file="/WEB-INF/jsp/include.jsp" %>

<a href="welcome.htm"><fmt:message key="quicklinks.welcome" /></a>
<a href="streamingconfiguration.htm"><fmt:message key="quicklinks.configuration" /></a>
<a href="dttchannellist.htm"><fmt:message key="quicklinks.dtt" /></a>
<a href="satchannellist.htm"><fmt:message key="quicklinks.satellites" /></a>
<a href="filechannellist.htm"><fmt:message key="quicklinks.files" /></a>
<a href="streamchannellist.htm"><fmt:message key="quicklinks.streams" /></a>
<a href="ordermonitor.htm"><fmt:message key="quicklinks.orders" /></a>
<a class="active" href="serverlist.htm"><fmt:message key="quicklinks.servers" /></a>

vlma-webapp/src/main/webapp/WEB-INF/jsp/server/server_left.jsp
<%@ include file="/WEB-INF/jsp/include.jsp" %>

<ul>
    <li><a href="serverlist.htm"><fmt:message key="servers.list" /></a></li>
    <li><a href="serveradd.htm"><fmt:message key="servers.add" /></a></li>
    <li><a href="serverstartcheckvlc.htm"><fmt:message key="servers.startcheckvlc" /></a></li>
    <li><a href="servermonitoring.htm"><fmt:message key="servers.graphs" /></a></li>
</ul>

vlma-webapp/src/main/webapp/WEB-INF/jsp/server/serveradapteradd_right.jsp
<%@ include file="/WEB-INF/jsp/include.jsp" %>

<h1>
    <fmt:message key="servers.adapter.adding">
        <fmt:param value="${server.name}" />
    </fmt:message>
</h1>

<script type="text/javascript">
function toggleGetSatellite() {
    var getType = document.getElementById("getTypeSelect");
    var getSatellite = document.getElementById("getSatelliteTr");
    if (getType.options[getType.selectedIndex].text != "DVB-S") {
        getSatellite.style.visibility = "hidden";
    } else {
        getSatellite.style.visibility = "visible";
    }
}
</script>

<form method="post">
<table>
    <tr>
        <td align="right"><fmt:message key="servers.adapter.add.name" /></td>
        <spring:bind path="serverAdapterAdd.name">
            <td><input type="text" name="name"
                value="<c:out value="${status.value}"/>"></td>
            <td><span class="error"><c:out
                value="${status.errorMessage}" /></span></td>
        </spring:bind>
    </tr>
    <tr>
        <td align="right"><fmt:message key="servers.adapter.add.type" /></td>
        <spring:bind path="serverAdapterAdd.type">
            <td>
                <select name="type" id="getTypeSelect" onchange="toggleGetSatellite()">
                    <option>DVB-S</option>
                    <option>DVB-T</option>
                </select>
            </td>
            <td><span class="error"><c:out
                value="${status.errorMessage}" /></span></td>
        </spring:bind>
    </tr>
    <tr id="getSatelliteTr">
        <td align="right"><fmt:message key="servers.adapter.add.satellite" /></td>
        <spring:bind path="serverAdapterAdd.satellite">
            <td>
                <select name="satellite">
                    <c:forEach items="${satellites}" var="satellite">
                        <option value="<c:out value="${satellite.id}" />"><c:out value="${satellite.name}" /></option>
                    </c:forEach>
                </select>
            </td>
            <td><span class="error"><c:out
                value="${status.errorMessage}" /></span></td>
        </spring:bind>
    </tr>
</table>
<spring:hasBindErrors name="serverAdapterAdd">
    <b><fmt:message key="servers.adapter.add.error.fix" /></b>
</spring:hasBindErrors>
<br />
<input type="submit" value="<fmt:message key="servers.adapter.add.run" />">
</form>

<script type="text/javascript">
toggleGetSatellite();
</script>

<div class="help">
<table><tr><td style="width: 30px">
<img src="<c:url value="/img/help.png" />" alt="Help" />
</td><td>
<fmt:message key="servers.adapter.help" />
</td></tr></table>
</div>

vlma-webapp/src/main/webapp/WEB-INF/jsp/server/serveradapterremove_right.jsp
<%@ include file="/WEB-INF/jsp/include.jsp"%>

<h1>
    <fmt:message key="servers.adapter.removing">
        <fmt:param value="${adapter.name}" />
        <fmt:param value="${server.name}" />
    </fmt:message>
</h1>

<form method="post">

<fmt:message key="servers.adapter.remove.text">
    <fmt:param value="${adapter.name}" />
    <fmt:param value="${server.name}" />
</fmt:message>

<spring:hasBindErrors name="serversAdapterRemove">
    <b><fmt:message key="servers.adapter.remove.error.fix" /></b>
</spring:hasBindErrors> <br />

<input type="submit" value="<fmt:message key="servers.adapter.remove.run" />">

</form>

vlma-webapp/src/main/webapp/WEB-INF/jsp/server/serveradd_right.jsp
<%@ include file="/WEB-INF/jsp/include.jsp"%>

<h1><fmt:message key="servers.adding" /></h1>

<form method="post">
<table>
    <tr>
        <td align="right"><fmt:message key="servers.add.name" /></td>
        <spring:bind path="serverAdd.name">
            <td><input type="text" name="name"
                value="<c:out value="${status.value}"/>"></td>
            <td><span class="error"><c:out
                value="${status.errorMessage}" /></span></td>
        </spring:bind>
    </tr>
    <tr>
        <td align="right"><fmt:message key="servers.add.address" /></td>
        <spring:bind path="serverAdd.address">
            <td><input type="text" name="address"
                value="<c:out value="${status.value}"/>"></td>
            <td><span class="error"><c:out
                value="${status.errorMessage}" /></span></td>
        </spring:bind>
    </tr>
</table>
<spring:hasBindErrors name="serversAdd">
    <b><fmt:message key="servers.add.error.fix" /></b>
</spring:hasBindErrors>
<br />
<input type="submit" value="<fmt:message key="servers.add.run" />">
</form>

vlma-webapp/src/main/webapp/WEB-INF/jsp/server/serverlist_right.jsp
<%@ include file="/WEB-INF/jsp/include.jsp" %>

<h1><fmt:message key="servers.list" /></h1>

<c:choose>
<c:when test="${empty servers}">
    <p><fmt:message key="servers.empty" /></p>
</c:when>
<c:otherwise>

<table width="80%">
    <c:forEach items="${servers}" var="server">
    <c:url value="serverview.htm" var="serversViewUrl">
        <c:param name="server" value="${server.id}" />
    </c:url>
    <c:url value="serverremove.htm" var="serversRemoveUrl">
        <c:param name="server" value="${server.id}" />
    </c:url>
    <tr>
        <td width="25%"><b><c:out value="${server.name}" /></b></td>
        <td><c:out value="${server.ip.hostName} / ${server.ip.hostAddress}" /></td>
        <td>
            <c:if test="${!server.up}">
                <span class="error"><fmt:message key="servers.unreachable" /></span>
            </c:if>
        </td>
        <td>
            <a href="${serversViewUrl}"><img src="<c:url value="/img/edit.png" />" title="<fmt:message key="servers.details" />" /></a>
            <a href="${serversRemoveUrl}"><img src="<c:url value="/img/delete.png" />" title="<fmt:message key="servers.remove" />" /></a>
        </td>
    </tr>
    </c:forEach>
</table>

</c:otherwise>
</c:choose>

vlma-webapp/src/main/webapp/WEB-INF/jsp/server/serverremove_right.jsp
<%@ include file="/WEB-INF/jsp/include.jsp"%>

<h1>
    <fmt:message key="servers.removing">
        <fmt:param value="${server.name}" />
    </fmt:message>
</h1>

<form method="post">

<fmt:message key="servers.remove.text">
    <fmt:param value="${server.name}" />
</fmt:message>

<spring:hasBindErrors name="serversRemove">
    <b><fmt:message key="servers.remove.error.fix" /></b>
</spring:hasBindErrors> <br />

<input type="submit" value="<fmt:message key="servers.remove.run" />">

</form>

vlma-webapp/src/main/webapp/WEB-INF/jsp/server/serverstartcheckvlc_right.jsp
<%@ include file="/WEB-INF/jsp/include.jsp" %>

<h1><fmt:message key="servers.startcheckvlc.page" /></h1>

<p>
    <fmt:message key="servers.startcheckvlc.text" />
</p>

<script type="text/javascript">
setTimeout('redirect("serverlist.htm")', 2500)
</script>

vlma-webapp/src/main/webapp/WEB-INF/jsp/server/serverview_right.jsp
<%@ include file="/WEB-INF/jsp/include.jsp" %>

<h1>
    <fmt:message key="servers.view">
        <fmt:param value="${server.name}" />
    </fmt:message>
</h1>

<ul>
    <li><fmt:message key="servers.view.name" /> <b><c:out value="${server.name}" /></b></li>
    <c:if test="${vlcVersion != null}">
        <li><b><c:out value="${vlcVersion}" /></b></li>
    </c:if>
    <c:if test="${vlcUptime != null}">
        <fmt:message key="general.days" var="days" />
        <li><fmt:message key="servers.view.vlc.uptime"><fmt:param value="${vlcUptime.days} ${days}, ${vlcUptime.hours}" /></fmt:message></li>
    </c:if>
    <li><fmt:message key="servers.view.address" /> <b><c:out value="${server.ip.hostName} / ${server.ip.hostAddress}" /></b></li>
    <li><fmt:message key="servers.view.adapters" />
        <table>
        <c:forEach items="${server.adapters}" var="adapter">
            <c:if test="${fn:contains(adapter.class, 'DVB')}">
            <tr><td><b><c:out value="${adapter.name}" /></b>
                <c:choose>
                    <c:when test="${fn:contains(adapter.class, 'DVBS')}">
                        <fmt:message key="servers.view.adapters.dvbs"><fmt:param value="${adapter.satellite.name}" /></fmt:message>
                    </c:when>
                    <c:when test="${fn:contains(adapter.class, 'DVBT')}">
                        <fmt:message key="servers.view.adapters.dvbt" />
                    </c:when>
                </c:choose>
                <c:url value="serveradapterremove.htm" var="adapterRemoveUrl">
                    <c:param name="server" value="${server.id}" />
                    <c:param name="adapter" value="${adapter.name}" />
                </c:url></td>
                <td><a href="${adapterRemoveUrl}"><img src="<c:url value="/img/delete.png" />" title="<fmt:message key="servers.view.adapters.remove" />" /></a></td>
            </tr>
            </c:if>
        </c:forEach>
        </table>
        <c:url value="serveradapteradd.htm" var="adapterAddUrl">
            <c:param name="server" value="${server.id}" />
        </c:url>
        <a href="${adapterAddUrl}"><fmt:message key="servers.view.adapters.add" /></a>
    </li>
    <c:if test="${graphsEnabled}">
	    <li><fmt:message key="servers.view.monitoring.load" /><br />
	        <img alt="<fmt:message key="servers.view.monitoring.load-alt" />" src="<c:url value="/" />rrdgraph?server=<c:out value="${server.name}" />&what=cpu_load" />
	    </li>
	    <li><fmt:message key="servers.view.monitoring.traffic" /><br />
	        <img alt="<fmt:message key="servers.view.monitoring.traffic-alt" />" src="<c:url value="/" />rrdgraph?server=<c:out value="${server.name}" />&what=traffic" />
	    </li>
	    <li><fmt:message key="servers.view.monitoring.resources" /><br />
	        <img alt="<fmt:message key="servers.view.monitoring.resources-alt" />" src="<c:url value="/" />rrdgraph?server=<c:out value="${server.name}" />&what=vlc" />
	    </li>
	</c:if>
    <c:if test="${vlcLogs != null}">
        <li><b><fmt:message key="servers.view.vlc.logs" /></b><br />
        <c:forEach items="${vlcLogs}" var="log">
            <c:out value="${log}" /><br />
        </c:forEach>
        </li>
    </c:if>
</ul>